//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelEden {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpanishResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpanishResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelEden.SpanishResources", typeof(SpanishResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jorge Gabuardi.
        /// </summary>
        public static string FooterAuthor {
            get {
                return ResourceManager.GetString("FooterAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Contamos con habitaciones simples, dobles, triples y cuadruples con banio privado. Las habitaciones son amplias, cuentan con television y cable y proveemos WiFi.&lt;/p&gt;&lt;p&gt;El hotel se encuentra en medio de Banios a pocos pasos de todas las atracciones turisticas.&lt;/p&gt;&lt;p&gt;Nuestro personal puede guiarlos en opciones y lugares disponibles para realizar paseos en bicicleta o motocicleta, canoas, rafting o actividades relajantes,.
        /// </summary>
        public static string HomeAmenitiesDetails {
            get {
                return ResourceManager.GetString("HomeAmenitiesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para hacer una reservacion, revise nuestras habitaciones disponibles o ingrese las fechas deseadas en la forma en la parte superior derecha de la pagina..
        /// </summary>
        public static string HomeInstructionsForReservations {
            get {
                return ResourceManager.GetString("HomeInstructionsForReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Aqui encontrara una estadia placentera mientras es atendido por gente amable y dispuesta a ayudarlo en todo lo necesario para que su visita sea inolvidable.&lt;/p&gt;.
        /// </summary>
        public static string HomeWelcomeDetails {
            get {
                return ResourceManager.GetString("HomeWelcomeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a Hostal El Eden!.
        /// </summary>
        public static string HomeWelcomeTitle {
            get {
                return ResourceManager.GetString("HomeWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostal El Eden.
        /// </summary>
        public static string HotelName {
            get {
                return ResourceManager.GetString("HotelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baños.
        /// </summary>
        public static string MenuBanos {
            get {
                return ResourceManager.GetString("MenuBanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string MenuContacto {
            get {
                return ResourceManager.GetString("MenuContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeria.
        /// </summary>
        public static string MenuGallery {
            get {
                return ResourceManager.GetString("MenuGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitaciones.
        /// </summary>
        public static string MenuRooms {
            get {
                return ResourceManager.GetString("MenuRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llegada.
        /// </summary>
        public static string ReserveFormArrivalDate {
            get {
                return ResourceManager.GetString("ReserveFormArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida.
        /// </summary>
        public static string ReserveFormDepartureDate {
            get {
                return ResourceManager.GetString("ReserveFormDepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ReserveFormEmail {
            get {
                return ResourceManager.GetString("ReserveFormEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string ReserveFormFirstName {
            get {
                return ResourceManager.GetString("ReserveFormFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string ReserveFormLastName {
            get {
                return ResourceManager.GetString("ReserveFormLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. de Personas.
        /// </summary>
        public static string ReserveFormNumPeople {
            get {
                return ResourceManager.GetString("ReserveFormNumPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitacion.
        /// </summary>
        public static string ReserveFormRoomTypeName {
            get {
                return ResourceManager.GetString("ReserveFormRoomTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservar.
        /// </summary>
        public static string ReserveFormSubmit {
            get {
                return ResourceManager.GetString("ReserveFormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string ReserveFormTelephone {
            get {
                return ResourceManager.GetString("ReserveFormTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total = {0} personas X ${1} USD = $.
        /// </summary>
        public static string ReserveFormTotal {
            get {
                return ResourceManager.GetString("ReserveFormTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservar por email porque????.
        /// </summary>
        public static string ReservePageDescription {
            get {
                return ResourceManager.GetString("ReservePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservar Habitacion.
        /// </summary>
        public static string ReservePageTitle {
            get {
                return ResourceManager.GetString("ReservePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-3.jpg.
        /// </summary>
        public static string RoomDoubleImageURL {
            get {
                return ResourceManager.GetString("RoomDoubleImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoubleMatrimonial.
        /// </summary>
        public static string RoomDoubleMatrimonialKeyword {
            get {
                return ResourceManager.GetString("RoomDoubleMatrimonialKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string RoomDoubleMaxGuests {
            get {
                return ResourceManager.GetString("RoomDoubleMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoubleSimple.
        /// </summary>
        public static string RoomDoubleSimpleKeyword {
            get {
                return ResourceManager.GetString("RoomDoubleSimpleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string RoomDoubleSimpleMaxGuests {
            get {
                return ResourceManager.GetString("RoomDoubleSimpleMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatrimonialAndDoubleSimple.
        /// </summary>
        public static string RoomMatrimonialAndDoubleSimpleKeyword {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndDoubleSimpleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatrimonialAndSimple.
        /// </summary>
        public static string RoomMatrimonialAndSimpleKeyword {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndSimpleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrimonial.
        /// </summary>
        public static string RoomMatrimonialKeyword {
            get {
                return ResourceManager.GetString("RoomMatrimonialKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string RoomMatrimonialMaxGuests {
            get {
                return ResourceManager.GetString("RoomMatrimonialMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-7.jpg.
        /// </summary>
        public static string RoomQuadrupleIURL {
            get {
                return ResourceManager.GetString("RoomQuadrupleIURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string RoomQuadrupleMaxGuests {
            get {
                return ResourceManager.GetString("RoomQuadrupleMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuadrupleSimple.
        /// </summary>
        public static string RoomQuadrupleSimpleKeyword {
            get {
                return ResourceManager.GetString("RoomQuadrupleSimpleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to costo.
        /// </summary>
        public static string RoomsCostColumn {
            get {
                return ResourceManager.GetString("RoomsCostColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cant. cuartos.
        /// </summary>
        public static string RoomsCountColumn {
            get {
                return ResourceManager.GetString("RoomsCountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion sencilla!.
        /// </summary>
        public static string RoomSingleDescription {
            get {
                return ResourceManager.GetString("RoomSingleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-1.jpg.
        /// </summary>
        public static string RoomSingleImageURL {
            get {
                return ResourceManager.GetString("RoomSingleImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string RoomSingleKeyword {
            get {
                return ResourceManager.GetString("RoomSingleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string RoomSingleMaxGuests {
            get {
                return ResourceManager.GetString("RoomSingleMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.50.
        /// </summary>
        public static string RoomSingleRate {
            get {
                return ResourceManager.GetString("RoomSingleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very short description single!&lt;ul&gt;&lt;li&gt;test&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string RoomSingleShortDescription {
            get {
                return ResourceManager.GetString("RoomSingleShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-1_thumb.jpg.
        /// </summary>
        public static string RoomSingleThumbURL {
            get {
                return ResourceManager.GetString("RoomSingleThumbURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitacion Sencilla.
        /// </summary>
        public static string RoomSingleTitle {
            get {
                return ResourceManager.GetString("RoomSingleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string RoomSingleURL {
            get {
                return ResourceManager.GetString("RoomSingleURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Hostal El Eden contamos con ...... que mas aqui?.
        /// </summary>
        public static string RoomsPageDescription {
            get {
                return ResourceManager.GetString("RoomsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to personas por cuarto.
        /// </summary>
        public static string RoomsReservePeoplePerRoom {
            get {
                return ResourceManager.GetString("RoomsReservePeoplePerRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        public static string RoomsReserveTotalColumn {
            get {
                return ResourceManager.GetString("RoomsReserveTotalColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De {0} a {1}.
        /// </summary>
        public static string RoomsSearchDescription {
            get {
                return ResourceManager.GetString("RoomsSearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string RoomsSelectRoom {
            get {
                return ResourceManager.GetString("RoomsSelectRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitaciones.
        /// </summary>
        public static string RoomsTitle {
            get {
                return ResourceManager.GetString("RoomsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-4.jpg.
        /// </summary>
        public static string RoomTripleImageURL {
            get {
                return ResourceManager.GetString("RoomTripleImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string RoomTripleMaxGuests {
            get {
                return ResourceManager.GetString("RoomTripleMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TripleSimple.
        /// </summary>
        public static string RoomTripleSimpleKeyword {
            get {
                return ResourceManager.GetString("RoomTripleSimpleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        public static string SiteHomeTitle {
            get {
                return ResourceManager.GetString("SiteHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostal El Eden.
        /// </summary>
        public static string SiteMainTitle {
            get {
                return ResourceManager.GetString("SiteMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservar.
        /// </summary>
        public static string SiteRoomsReserve {
            get {
                return ResourceManager.GetString("SiteRoomsReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmacion.
        /// </summary>
        public static string SiteRoomsSuccess {
            get {
                return ResourceManager.GetString("SiteRoomsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitaciones.
        /// </summary>
        public static string SiteRoomsTitle {
            get {
                return ResourceManager.GetString("SiteRoomsTitle", resourceCulture);
            }
        }
    }
}
