//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelEden {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpanishResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpanishResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HotelEden.SpanishResources", typeof(SpanishResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estamos a su disposicion para cualquier duda o comentario. Puede contactarnos por email a gabosom@gmail.com o llene la forma y responderemos lo mas pronto posible..
        /// </summary>
        public static string ContactDescription {
            get {
                return ResourceManager.GetString("ContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string ContactFormName {
            get {
                return ResourceManager.GetString("ContactFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregunta o Comentario.
        /// </summary>
        public static string ContactFormTitle {
            get {
                return ResourceManager.GetString("ContactFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se ha enviado la informacion exitosamente. Nos pondremos en contacto pronto..
        /// </summary>
        public static string ContactSentDetails {
            get {
                return ResourceManager.GetString("ContactSentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string ContactSubmit {
            get {
                return ResourceManager.GetString("ContactSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jorge Gabuardi.
        /// </summary>
        public static string FooterAuthor {
            get {
                return ResourceManager.GetString("FooterAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeria.
        /// </summary>
        public static string GalleryTitle {
            get {
                return ResourceManager.GetString("GalleryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Contamos con habitaciones simples, dobles, triples y cuadruples con banio privado. Las habitaciones son amplias, cuentan con television y cable y proveemos WiFi.&lt;/p&gt;&lt;p&gt;El hotel se encuentra en medio de Banios a pocos pasos de todas las atracciones turisticas.&lt;/p&gt;&lt;p&gt;Nuestro personal puede guiarlos en opciones y lugares disponibles para realizar paseos en bicicleta o motocicleta, canoas, rafting o actividades relajantes,.
        /// </summary>
        public static string HomeAmenitiesDetails {
            get {
                return ResourceManager.GetString("HomeAmenitiesDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para hacer una reservacion, revise nuestras habitaciones disponibles o ingrese las fechas deseadas en la forma en la parte superior derecha de la pagina..
        /// </summary>
        public static string HomeInstructionsForReservations {
            get {
                return ResourceManager.GetString("HomeInstructionsForReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Aqui encontrara una estadia placentera mientras es atendido por gente amable y dispuesta a ayudarlo en todo lo necesario para que su visita sea inolvidable.&lt;/p&gt;.
        /// </summary>
        public static string HomeWelcomeDetails {
            get {
                return ResourceManager.GetString("HomeWelcomeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a Hostal El Eden!.
        /// </summary>
        public static string HomeWelcomeTitle {
            get {
                return ResourceManager.GetString("HomeWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostal El Eden.
        /// </summary>
        public static string HotelName {
            get {
                return ResourceManager.GetString("HotelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baños.
        /// </summary>
        public static string MenuBanos {
            get {
                return ResourceManager.GetString("MenuBanos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        public static string MenuContacto {
            get {
                return ResourceManager.GetString("MenuContacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Galeria.
        /// </summary>
        public static string MenuGallery {
            get {
                return ResourceManager.GetString("MenuGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitaciones.
        /// </summary>
        public static string MenuRooms {
            get {
                return ResourceManager.GetString("MenuRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noches.
        /// </summary>
        public static string NightsLowercase {
            get {
                return ResourceManager.GetString("NightsLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llegada.
        /// </summary>
        public static string ReserveFormArrivalDate {
            get {
                return ResourceManager.GetString("ReserveFormArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salida.
        /// </summary>
        public static string ReserveFormDepartureDate {
            get {
                return ResourceManager.GetString("ReserveFormDepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ReserveFormEmail {
            get {
                return ResourceManager.GetString("ReserveFormEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string ReserveFormFirstName {
            get {
                return ResourceManager.GetString("ReserveFormFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string ReserveFormLastName {
            get {
                return ResourceManager.GetString("ReserveFormLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. de Personas.
        /// </summary>
        public static string ReserveFormNumPeople {
            get {
                return ResourceManager.GetString("ReserveFormNumPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitacion.
        /// </summary>
        public static string ReserveFormRoomTypeName {
            get {
                return ResourceManager.GetString("ReserveFormRoomTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservar.
        /// </summary>
        public static string ReserveFormSubmit {
            get {
                return ResourceManager.GetString("ReserveFormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono.
        /// </summary>
        public static string ReserveFormTelephone {
            get {
                return ResourceManager.GetString("ReserveFormTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total = {0} personas X ${1} USD = $.
        /// </summary>
        public static string ReserveFormTotal {
            get {
                return ResourceManager.GetString("ReserveFormTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservar por email porque????.
        /// </summary>
        public static string ReservePageDescription {
            get {
                return ResourceManager.GetString("ReservePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservar Habitacion.
        /// </summary>
        public static string ReservePageTitle {
            get {
                return ResourceManager.GetString("ReservePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoubleMatrimonial desc.
        /// </summary>
        public static string RoomDoubleMatrimonialDescription {
            get {
                return ResourceManager.GetString("RoomDoubleMatrimonialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-4.jpg.
        /// </summary>
        public static string RoomDoubleMatrimonialImageURL {
            get {
                return ResourceManager.GetString("RoomDoubleMatrimonialImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoubleMatrimonial.
        /// </summary>
        public static string RoomDoubleMatrimonialKeyword {
            get {
                return ResourceManager.GetString("RoomDoubleMatrimonialKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string RoomDoubleMatrimonialMaxGuests {
            get {
                return ResourceManager.GetString("RoomDoubleMatrimonialMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoubleMatrimonial short@.
        /// </summary>
        public static string RoomDoubleMatrimonialShortDescription {
            get {
                return ResourceManager.GetString("RoomDoubleMatrimonialShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-4.jpg.
        /// </summary>
        public static string RoomDoubleMatrimonialThumbURL {
            get {
                return ResourceManager.GetString("RoomDoubleMatrimonialThumbURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 matrimoniales.
        /// </summary>
        public static string RoomDoubleMatrimonialTitle {
            get {
                return ResourceManager.GetString("RoomDoubleMatrimonialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoubleMatrimonial.
        /// </summary>
        public static string RoomDoubleMatrimonialURL {
            get {
                return ResourceManager.GetString("RoomDoubleMatrimonialURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string RoomDoubleMaxGuests {
            get {
                return ResourceManager.GetString("RoomDoubleMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion double single.
        /// </summary>
        public static string RoomDoubleSimpleDescription {
            get {
                return ResourceManager.GetString("RoomDoubleSimpleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-2.jpg.
        /// </summary>
        public static string RoomDoubleSimpleImageURL {
            get {
                return ResourceManager.GetString("RoomDoubleSimpleImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoubleSimple.
        /// </summary>
        public static string RoomDoubleSimpleKeyword {
            get {
                return ResourceManager.GetString("RoomDoubleSimpleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string RoomDoubleSimpleMaxGuests {
            get {
                return ResourceManager.GetString("RoomDoubleSimpleMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22.4.
        /// </summary>
        public static string RoomDoubleSimpleRate {
            get {
                return ResourceManager.GetString("RoomDoubleSimpleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short desc shortsimpoe.
        /// </summary>
        public static string RoomDoubleSimpleShortDescription {
            get {
                return ResourceManager.GetString("RoomDoubleSimpleShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-2.jpg.
        /// </summary>
        public static string RoomDoubleSimpleThumbURL {
            get {
                return ResourceManager.GetString("RoomDoubleSimpleThumbURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 camas sencillas.
        /// </summary>
        public static string RoomDoubleSimpleTitle {
            get {
                return ResourceManager.GetString("RoomDoubleSimpleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to doublesimple.
        /// </summary>
        public static string RoomDoubleSimpleURL {
            get {
                return ResourceManager.GetString("RoomDoubleSimpleURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatrimonialAndDoubleSimple description.
        /// </summary>
        public static string RoomMatrimonialAndDoubleSimpleDescription {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndDoubleSimpleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-4.jpg.
        /// </summary>
        public static string RoomMatrimonialAndDoubleSimpleImageURL {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndDoubleSimpleImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatrimonialAndDoubleSimple.
        /// </summary>
        public static string RoomMatrimonialAndDoubleSimpleKeyword {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndDoubleSimpleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string RoomMatrimonialAndDoubleSimpleMaxGuests {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndDoubleSimpleMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatrimonialAndDoubleSimple short desc.
        /// </summary>
        public static string RoomMatrimonialAndDoubleSimpleShortDescription {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndDoubleSimpleShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-4.jpg.
        /// </summary>
        public static string RoomMatrimonialAndDoubleSimpleThumbURL {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndDoubleSimpleThumbURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 matrimonial y 2 sencillas.
        /// </summary>
        public static string RoomMatrimonialAndDoubleSimpleTitle {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndDoubleSimpleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatrimonialAndDoubleSimple.
        /// </summary>
        public static string RoomMatrimonialAndDoubleSimpleURL {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndDoubleSimpleURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mat and simple desc.
        /// </summary>
        public static string RoomMatrimonialAndSimpleDescription {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndSimpleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-4.jpg.
        /// </summary>
        public static string RoomMatrimonialAndSimpleImageURL {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndSimpleImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatrimonialAndSimple.
        /// </summary>
        public static string RoomMatrimonialAndSimpleKeyword {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndSimpleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string RoomMatrimonialAndSimpleMaxGuests {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndSimpleMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatrimonialAndSimple short desc.
        /// </summary>
        public static string RoomMatrimonialAndSimpleShortDescription {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndSimpleShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-4.jpg.
        /// </summary>
        public static string RoomMatrimonialAndSimpleThumbURL {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndSimpleThumbURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 matrimonial y 1 sencillas.
        /// </summary>
        public static string RoomMatrimonialAndSimpleTitle {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndSimpleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatrimonialAndSimple.
        /// </summary>
        public static string RoomMatrimonialAndSimpleURL {
            get {
                return ResourceManager.GetString("RoomMatrimonialAndSimpleURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripcion sencilla!.
        /// </summary>
        public static string RoomMatrimonialDescription {
            get {
                return ResourceManager.GetString("RoomMatrimonialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-1.jpg.
        /// </summary>
        public static string RoomMatrimonialImageURL {
            get {
                return ResourceManager.GetString("RoomMatrimonialImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrimonial.
        /// </summary>
        public static string RoomMatrimonialKeyword {
            get {
                return ResourceManager.GetString("RoomMatrimonialKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string RoomMatrimonialMaxGuests {
            get {
                return ResourceManager.GetString("RoomMatrimonialMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.50.
        /// </summary>
        public static string RoomMatrimonialRate {
            get {
                return ResourceManager.GetString("RoomMatrimonialRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very short description single!&lt;ul&gt;&lt;li&gt;test&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        public static string RoomMatrimonialShortDescription {
            get {
                return ResourceManager.GetString("RoomMatrimonialShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-1.jpg.
        /// </summary>
        public static string RoomMatrimonialThumbURL {
            get {
                return ResourceManager.GetString("RoomMatrimonialThumbURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 matrimonial.
        /// </summary>
        public static string RoomMatrimonialTitle {
            get {
                return ResourceManager.GetString("RoomMatrimonialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string RoomMatrimonialURL {
            get {
                return ResourceManager.GetString("RoomMatrimonialURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-7.jpg.
        /// </summary>
        public static string RoomQuadrupleIURL {
            get {
                return ResourceManager.GetString("RoomQuadrupleIURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string RoomQuadrupleMaxGuests {
            get {
                return ResourceManager.GetString("RoomQuadrupleMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  QuadrupleSimple desc.
        /// </summary>
        public static string RoomQuadrupleSimpleDescription {
            get {
                return ResourceManager.GetString("RoomQuadrupleSimpleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-4.jpg.
        /// </summary>
        public static string RoomQuadrupleSimpleImageURL {
            get {
                return ResourceManager.GetString("RoomQuadrupleSimpleImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuadrupleSimple.
        /// </summary>
        public static string RoomQuadrupleSimpleKeyword {
            get {
                return ResourceManager.GetString("RoomQuadrupleSimpleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        public static string RoomQuadrupleSimpleMaxGuests {
            get {
                return ResourceManager.GetString("RoomQuadrupleSimpleMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  QuadrupleSimple short.
        /// </summary>
        public static string RoomQuadrupleSimpleShortDescription {
            get {
                return ResourceManager.GetString("RoomQuadrupleSimpleShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-4.jpg.
        /// </summary>
        public static string RoomQuadrupleSimpleThumbURL {
            get {
                return ResourceManager.GetString("RoomQuadrupleSimpleThumbURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 simples.
        /// </summary>
        public static string RoomQuadrupleSimpleTitle {
            get {
                return ResourceManager.GetString("RoomQuadrupleSimpleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuadrupleSimple.
        /// </summary>
        public static string RoomQuadrupleSimpleURL {
            get {
                return ResourceManager.GetString("RoomQuadrupleSimpleURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continuar.
        /// </summary>
        public static string RoomsContinueAsValid {
            get {
                return ResourceManager.GetString("RoomsContinueAsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to costo por noche.
        /// </summary>
        public static string RoomsCostColumn {
            get {
                return ResourceManager.GetString("RoomsCostColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cant. cuartos.
        /// </summary>
        public static string RoomsCountColumn {
            get {
                return ResourceManager.GetString("RoomsCountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Hostal El Eden contamos con ...... que mas aqui?.
        /// </summary>
        public static string RoomsPageDescription {
            get {
                return ResourceManager.GetString("RoomsPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to personas por cuarto.
        /// </summary>
        public static string RoomsReservePeoplePerRoom {
            get {
                return ResourceManager.GetString("RoomsReservePeoplePerRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string RoomsReserveTotal {
            get {
                return ResourceManager.GetString("RoomsReserveTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total.
        /// </summary>
        public static string RoomsReserveTotalColumn {
            get {
                return ResourceManager.GetString("RoomsReserveTotalColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De {0} a {1}.
        /// </summary>
        public static string RoomsSearchDescription {
            get {
                return ResourceManager.GetString("RoomsSearchDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionar.
        /// </summary>
        public static string RoomsSelectRoom {
            get {
                return ResourceManager.GetString("RoomsSelectRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitaciones.
        /// </summary>
        public static string RoomsTitle {
            get {
                return ResourceManager.GetString("RoomsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione 1 habit. minimo.
        /// </summary>
        public static string RoomsValidateCount {
            get {
                return ResourceManager.GetString("RoomsValidateCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-4.jpg.
        /// </summary>
        public static string RoomTripleImageURL {
            get {
                return ResourceManager.GetString("RoomTripleImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string RoomTripleMaxGuests {
            get {
                return ResourceManager.GetString("RoomTripleMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TripleSimple desc.
        /// </summary>
        public static string RoomTripleSimpleDescription {
            get {
                return ResourceManager.GetString("RoomTripleSimpleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-4.jpg.
        /// </summary>
        public static string RoomTripleSimpleImageURL {
            get {
                return ResourceManager.GetString("RoomTripleSimpleImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TripleSimple.
        /// </summary>
        public static string RoomTripleSimpleKeyword {
            get {
                return ResourceManager.GetString("RoomTripleSimpleKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        public static string RoomTripleSimpleMaxGuests {
            get {
                return ResourceManager.GetString("RoomTripleSimpleMaxGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple simple short description.
        /// </summary>
        public static string RoomTripleSimpleShortDescriptiin {
            get {
                return ResourceManager.GetString("RoomTripleSimpleShortDescriptiin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TripleSimple short desc.
        /// </summary>
        public static string RoomTripleSimpleShortDescription {
            get {
                return ResourceManager.GetString("RoomTripleSimpleShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoomPictures/gallery-4.jpg.
        /// </summary>
        public static string RoomTripleSimpleThumbURL {
            get {
                return ResourceManager.GetString("RoomTripleSimpleThumbURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 sencillas.
        /// </summary>
        public static string RoomTripleSimpleTitle {
            get {
                return ResourceManager.GetString("RoomTripleSimpleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TripleSimple.
        /// </summary>
        public static string RoomTripleSimpleURL {
            get {
                return ResourceManager.GetString("RoomTripleSimpleURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido.
        /// </summary>
        public static string SiteHomeTitle {
            get {
                return ResourceManager.GetString("SiteHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostal El Eden.
        /// </summary>
        public static string SiteMainTitle {
            get {
                return ResourceManager.GetString("SiteMainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservar.
        /// </summary>
        public static string SiteRoomsReserve {
            get {
                return ResourceManager.GetString("SiteRoomsReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmacion.
        /// </summary>
        public static string SiteRoomsSuccess {
            get {
                return ResourceManager.GetString("SiteRoomsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habitaciones.
        /// </summary>
        public static string SiteRoomsTitle {
            get {
                return ResourceManager.GetString("SiteRoomsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Se ha enviado la solicitud y uno de nuestros representantes se pondra en contacto pronto con usted para finalizar la reservacion.,&lt;/p&gt;&lt;p&gt;Recomendamos que lea la seccion de Banos para que se familiarize con las acrividades que puede hacer aca. &lt;/p&gt;&lt;p&gt;Lo vemos pronto!&lt;/p&gt;.
        /// </summary>
        public static string SuccessDetails {
            get {
                return ResourceManager.GetString("SuccessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud Enviada.
        /// </summary>
        public static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese un email correcto.
        /// </summary>
        public static string ValidationIncorrectEmail {
            get {
                return ResourceManager.GetString("ValidationIncorrectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese una fecha de llegada.
        /// </summary>
        public static string ValidationRequiredCheckInDate {
            get {
                return ResourceManager.GetString("ValidationRequiredCheckInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese una fecha de salida.
        /// </summary>
        public static string ValidationRequiredCheckOutDate {
            get {
                return ResourceManager.GetString("ValidationRequiredCheckOutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su Email.
        /// </summary>
        public static string ValidationRequiredEmail {
            get {
                return ResourceManager.GetString("ValidationRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su Nombre.
        /// </summary>
        public static string ValidationRequiredFirstName {
            get {
                return ResourceManager.GetString("ValidationRequiredFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingrese su Apellido.
        /// </summary>
        public static string ValidationRequiredLastName {
            get {
                return ResourceManager.GetString("ValidationRequiredLastName", resourceCulture);
            }
        }
    }
}
